name: sparkio
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.13+32

environment:
  sdk: ^3.10.0

dependencies:
  firebase_analytics: ^11.4.0
  url_launcher: ^6.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  uuid: ^4.5.2
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  google_mobile_ads: ^7.0.0
  in_app_purchase: ^3.2.0
  share_plus: ^10.1.2
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.7
  firebase_core: ^3.6.0
  cloud_functions: ^5.0.0
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.2.0
  in_app_review: ^2.0.10
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/fonts/Inter-VariableFont_opsz,wght.ttf
    - assets/icon/sparkio_icon.png
    - assets/avatars/
    - assets/in_app_icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/sparkio_icon.png
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: assets/icon/sparkio_icon.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/sparkio_icon.png
  android_12:
    color: "#FFFFFF"
    image: assets/icon/sparkio_icon.png
  ios: true
  android: true


