// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8SDfWo9j7EWNmTz1h4bELqcQHRcg8NK4',
    appId: '1:855180124418:web:a4624e099c8603fa7e221b',
    messagingSenderId: '855180124418',
    projectId: 'sparkio-12345',
    authDomain: 'sparkio-12345.firebaseapp.com',
    storageBucket: 'sparkio-12345.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCdkJEUmgn-G__GdFSJ5hYzzGqUcGEz0s',
    appId: '1:855180124418:android:eb59d38590a634a37e221b',
    messagingSenderId: '855180124418',
    projectId: 'sparkio-12345',
    storageBucket: 'sparkio-12345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM16Nb1WS5oRTzseWwDybGzrK5cQUZTnU',
    appId: '1:855180124418:ios:8a9b65b2587990367e221b',
    messagingSenderId: '855180124418',
    projectId: 'sparkio-12345',
    storageBucket: 'sparkio-12345.firebasestorage.app',
    iosBundleId: 'com.example.sparkio',
  );
}
